---
- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- import_tasks: install_postgres.yml
  when:
    - pulp_install_db |bool

- meta: flush_handlers

- block:

    - name: Run database auth migrations
      command: '{{ pulp_install_dir }}/bin/django-admin migrate auth --no-input'
      register: migrate_auth
      changed_when: "'No migrations to apply' not in migrate_auth.stdout"

    - name: Run database migrations
      command: '{{ pulp_install_dir }}/bin/django-admin migrate --no-input'
      register: result
      changed_when: "'No migrations to apply' not in result.stdout"

    - name: Set the Pulp admin user's password
      command: '{{ pulp_install_dir }}/bin/django-admin reset-admin-password --password {{ pulp_default_admin_password }}'
      no_log: true
      when: pulp_default_admin_password is defined and migrate_auth.changed

  become: true
  become_user: '{{ pulp_user }}'
  environment:
    PULP_SETTINGS: "{{ pulp_settings_file }}"
