---

pulp_cache_dir: '/var/lib/pulp/tmp'
pulp_config_dir: '/etc/pulp'
# This var intentionally not advertised to users, because there is no
# foreseeable need for them to change the filename, only pulp_config_dir.
pulp_settings_file: '{{ pulp_config_dir }}/settings.py'
pulp_default_admin_password: ''
pulp_install_dir: '/usr/local/lib/pulp'
pulp_install_plugins: {}
pulp_install_api_service: true
pulp_install_source: pip
pulp_user: pulp
pulp_user_id:
pulp_group: pulp
pulp_group_id:
pulp_user_home: '/var/lib/pulp'
pulp_pip_editable: yes
pulp_use_system_wide_pkgs: false
pulp_api_bind: '127.0.0.1:24817'
prereq_pip_packages: []
rhel7_optional_repo:
  - rhui-rhel-7-server-rhui-optional-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-workstation-optional-rpms
epel_release_packages:
  - epel-release
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
