---
- block:

    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Install Apache configuration file
      template:
        src: pulp-vhost.conf.j2
        dest: /etc/httpd/conf.d/pulp-vhost.conf

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: restarted
        enabled: true
        daemon_reload: true

  become: true
