---
- name: Find pulpcore directory
  find:
    paths: '{{ pulp_install_dir }}'
    recurse: true
    file_type: directory
    patterns: pulpcore
  register: result

- name: Assert one directory has been found
  assert:
    that: '{{ result.matched }} == 1'

- name: Set fact referencing Pulp's static files directory
  set_fact:
    pulp_webserver_static_dir: '{{ (result.files[0].path~"/../rest_framework") | realpath }}'

- import_tasks: nginx.yml
  when: pulp_webserver_server == 'nginx'

- import_tasks: apache.yml
  when: pulp_webserver_server == 'apache'

- import_tasks: firewalld.yml
  when: pulp_configure_firewall in ['firewalld', 'auto']
