---
# installation of nginx on ubuntu doesn't do this automatically
- name: Create nginx user
  user:
    name: nginx
    system: true
  when: ansible_distribution == 'Ubuntu'
  become: yes

- block:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Install Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

  become: true
